Tests: add additional check for socat into tests/Makefile.am, in case it is ever removed from configure.ac
Strictly speaking it is not needed for installation of Snoopy, only for "make check"
phase which almost nobody runs.

diff --git a/tests/Makefile.am b/tests/Makefile.am
--- a/tests/Makefile.am
+++ b/tests/Makefile.am
@@ -6,7 +6,9 @@ include   $(top_srcdir)/build/Makefile.am.common
 
 ### Subdir processing order
 #
-SUBDIRS      =
+# Process this dir first, to check for dependencies
+#
+SUBDIRS      = .
 SUBDIRS     += bin
 if CONFIG_FILE_ENABLED
     SUBDIRS += configfile
@@ -17,3 +19,19 @@ if FILTERING_ENABLED
 endif
 SUBDIRS     += message
 SUBDIRS     += output
+
+
+
+### Make check - required programs
+#
+# Some of there tests are in configure.ac, but we keep
+# alternate copy here in case those in configure.ac are
+# removed
+#
+check-local:
+	if ! which socat > /dev/null ; then \
+	    echo ; \
+	    echo "ERROR: Program 'socat' not found!" ; \
+	    echo ; \
+	    exit 1 ; \
+	fi ;
